### ISSUE TITLE
借楼，有关问下您另一个项目

### ISSUE THREAD

**Issue by FrRay** [laizhangtu/BLS-YOLOV8-landslide_detector#1]
在您[校园网登录](https://github.com/laizhangtu/AutoLogin)项目中，功能"解除宽带限速"是否已失效？以下为多次尝试二次登录后测速(无多人连接、无代理)：
![image](https://github.com/user-attachments/assets/fe4281d0-3866-4adc-9958-946df7328585)

**Comment by laizhangtu** [comment]
> 在您[校园网登录](https://github.com/laizhangtu/AutoLogin)项目中，功能"解除宽带限速"是否已失效？以下为多次尝试二次登录后测速(无多人连接、无代理)： ![image](https://private-user-images.githubusercontent.com/76843279/385636666-fe4281d0-3866-4adc-9958-946df7328585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjAzODMsIm5iZiI6MTczMTU2MDA4MywicGF0aCI6Ii83Njg0MzI3OS8zODU2MzY2NjYtZmU0MjgxZDAtMzg2Ni00YWRjLTk5NTgtOTQ2ZGY3MzI4NTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA0NTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwM2Y1ZDFjNmY5ZDAyM2JiYTYxN2NlNTM0ZWEwNWQ0ZTdjNzEwM2NlYjU3ZGE2OTZkZTQ3MWJmOWM0OTRiNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VW7C7KkEtnJl5o36JHYkfS0gKr_7BXbTrsKYywok51o)

1. 请先确定用的是最新的.py脚本，.bat是未更改的
2. 目前解除限速靠的是多次登录来更改ip地址，至于这个ip我猜测是给校园网管理员使用的，所以说这个ip是固定的
3. 就我的测试来说，脚本是可用的，也可以看看原仓库的[PR14](https://github.com/flipped-1121/AutoLogin/pull/14)，那个是我用的版本
![屏幕截图 2024-11-14 125346](https://github.com/user-attachments/assets/114088f6-5c7c-4d54-b869-9205143af701)

**Comment by FrRay** [comment]
感谢您的解答！但我还有一些疑问：

- [get_public_ip()](https://github.com/laizhangtu/AutoLogin/blob/ca9f64a8be7ecf1367b0507d7957e5f9535f70b3/AutoLoginLite.py#L20)是返回ip各部分的数字和吗？如果我的IP数字之和是449（139.162.100.48），那么在主函数文件[第40行](https://github.com/laizhangtu/AutoLogin/blob/ca9f64a8be7ecf1367b0507d7957e5f9535f70b3/AutoLoginLite.py#L40)的判断范围应该怎么设置呀？
- 在[PR14](https://github.com/flipped-1121/AutoLogin/pull/14)中，[Get_IP.py](https://github.com/laizhangtu/AutoLogin/blob/lift-limits/Get_IP.py)看起并没有被调用；

- 等等！我连的是wifi是不行的吗？

期待您的回复！

**Comment by laizhangtu** [comment]
> 感谢您的解答！但我还有一些疑问：
> 
> * [get_public_ip()](https://github.com/laizhangtu/AutoLogin/blob/ca9f64a8be7ecf1367b0507d7957e5f9535f70b3/AutoLoginLite.py#L20)是返回ip各部分的数字和吗？如果我的IP数字之和是449（139.162.100.48），那么在主函数文件[第40行](https://github.com/laizhangtu/AutoLogin/blob/ca9f64a8be7ecf1367b0507d7957e5f9535f70b3/AutoLoginLite.py#L40)的判断范围应该怎么设置呀？
> * 在[PR14](https://github.com/flipped-1121/AutoLogin/pull/14)中，[Get_IP.py](https://github.com/laizhangtu/AutoLogin/blob/lift-limits/Get_IP.py)看起并没有被调用；
> * 等等！我连的是wifi是不行的吗？
> 
> 期待您的回复！

1. 对于第一个问题，你可以多尝试几次来看看你宿舍的不限速ip是什么，根据不限速的ip来确定范围，通常上下浮动5即可。
2. Get_IP.py是用来获取本机ip的，因为我看各个网站所得ip有可能不同，就写了这个来一开始确定ip地址。
3. WiFi按理应该是可行，不过我用的是网线，你可以尝试一下控制变量，欢迎你把实验结果告诉我 ^_^。

**Comment by FrRay** [comment]
- 多次登陆登出后，IP没有变化，还是限速；
- 通过网线登录，速率反而腰斩，推测可能是网线劣质，IP仍未变化（设置以太网那里用的是手动的IP分配）；
- 最后决定下载大文件时用手机开热点，还是非常感谢大佬提供思路。
[附上相关图片]
![image](https://github.com/user-attachments/assets/6b57eb7e-b18b-42f6-a538-56fe2a86c324)
![image](https://github.com/user-attachments/assets/7d5d2ec7-7256-48e4-82fb-6f3ddd343946)

**Comment by laizhangtu** [comment]
我是在平苑，经过测试室友也可使用，结合你的信息来看那估计就是只有平苑才行了。最后，还是非常感谢你的测试。
![image](https://github.com/user-attachments/assets/86933469-dc96-452e-84e0-25cb40286313)

**Comment by FrRay** [comment]
我也是平苑的，研一。您也是计算机院的吗？我在学院楼办公室，网线连接方式是导师教的，线材也是办公室的。太巧了，您愿意加个微信（号：proceedx）吗😁😍

**Comment by laizhangtu** [comment]
> 我也是平苑的，研一。您也是计算机院的吗？我在学院楼办公室，网线连接方式是导师教的，线材也是办公室的。太巧了，您愿意加个微信（号：proceedx）吗😁😍

不，我不是计算机院的，我也才刚大二，我很乐意进行更近一步的交流，已申请

**Comment by ForsakenDelusion** [comment]
居然真的秒破，太牛了
